// web/packages/shared-components-react/src/Search/index.tsx
import React, { useState, useRef, useEffect } from 'react'
import { Input } from 'antd'
import { SearchOutlined } from '@ant-design/icons'
import { SvgIcon } from '../SvgIcon'

export interface SearchProps {
  value?: string
  placeholder?: string
  text?: string
  size?: 'large' | 'middle' | 'small'
  disabled?: boolean
  className?: string
  onInput?: (value: string) => void
  onChange?: (value: string) => void
}

export const Search: React.FC<SearchProps> = ({
  value,
  placeholder,
  text,
  size = 'middle',
  disabled = false,
  className,
  onInput,
  onChange
}) => {
  const [input, setInput] = useState(value || '')
  const [searching, setSearching] = useState(false)
  const inputRef = useRef<any>(null)

  useEffect(() => {
    if (value !== undefined) {
      setInput(value)
    }
  }, [value])

  useEffect(() => {
    if (searching && inputRef.current) {
      inputRef.current.focus()
    }
  }, [searching])

  const handleFocus = () => {
    if (disabled) return
    setSearching(true)
  }

  const handleBlur = () => {
    if (input) return
    setSearching(false)
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value
    setInput(val)
    onInput?.(val)
  }

  const handlePressEnter = () => {
    onChange?.(input)
  }

  if (searching) {
    return (
      <Input
        ref={inputRef}
        value={input}
        onChange={handleInputChange}
        onBlur={handleBlur}
        onPressEnter={handlePressEnter}
        placeholder={placeholder || '搜索'}
        prefix={<SearchOutlined />}
        size={size}
        allowClear
        disabled={disabled}
        className={`input-with-search ${className || ''}`}
        style={{ maxWidth: '230px' }}
      />
    )
  }

  return (
    <div
      className={`h-8 flex items-center gap-1 ${
        disabled ? 'text-[#999] cursor-not-allowed' : 'cursor-pointer text-[#576D9C]'
      } ${className || ''}`}
      onClick={handleFocus}
    >
      <SvgIcon name="search" size={16} />
      <span className="text-sm">{text || '搜索'}</span>
    </div>
  )
}

export default Search

// web/packages/shared-components/src/Search/index.vue
<template>
  <el-input
    v-if="searching"
    ref="inputRef"
    v-model="input"
    style="max-width: 230px"
    size="default"
    clearable
    :prefix-icon="Search"
    :placeholder="placeholder || $t('shared_components.search_placeholder')"
    class="input-with-search"
    :disabled="disabled"
    @blur="handleBlur"
    @input="handleInput"
    @change="handleChange"
  />
  <div
    v-else
    class="h-8 flex items-center gap-1"
    :class="[disabled ? 'text-[#999] cursor-not-allowed' : 'cursor-pointer text-[#576D9C]']"
    @click="handleFocus"
  >
    <svg-icon name="search" width="16" />
    <span class="text-sm">{{ text || $t('shared_components.search_text') }}</span>
  </div>
</template>

<script setup lang="ts">
import { nextTick, ref } from 'vue';
import { Search } from '@element-plus/icons-vue';
import { debounce } from '@km/shared-utils';

const props = withDefaults(
  defineProps<{
    placeholder?: string
    text?: string
    size?: string
    disabled?: boolean
  }>(),
  {
    placeholder: '',
    text: '',
    size: 'default',
    disabled: false,
  },
)

const emits = defineEmits<{
  (e: 'input', value: string): void
  (e: 'change', value: string): void
}>()

const inputRef = ref()

const input = ref('')
const searching = ref(false)

const handleFocus = () => {
  if (props.disabled) return
  searching.value = true
  nextTick(() => {
    inputRef.value.focus()
  })
}
const handleBlur = () => {
  if (input.value) return
  searching.value = false
}

const handleInput = debounce(() => {
  emits('input', input.value)
}, 600)
const handleChange = debounce(() => {
  emits('change', input.value)
}, 0)
</script>

<style>
.input-with-search .el-input-group__prepend {
  padding: 0 10px;
  --el-fill-color-light: transparent;
}
.input-with-search .el-input-group__append {
  padding: 0 12px;
  cursor: pointer;
}
</style>
