// web/packages/shared-components/src/Sortable/index.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'

import Sortable from 'sortablejs'

const props = withDefaults(defineProps<{
  modelValue: any[]
  props?: any
  dragBg?: string
  identity?: string
  customSortableId?: string
  forceRender?: boolean
  infiniteScrollImmediate?: boolean
  infiniteScrollDistance?: number
  disabled?: boolean
  group?: string | {
    name: string
    pull?: boolean | string | ((to: any, from: any, dragEl: HTMLElement, evt: Event) => boolean)
    put?: boolean | string[] | ((to: any, from: any, dragEl: HTMLElement, evt: Event) => boolean)
    revertClone?: boolean
  }
  sort?: boolean
  allowCrossInstanceDrag?: boolean
}>(), {
  dragBg: '#ECF5FF',
  modelValue: () => [],
  identity: 'id',
  props: () => ({
    handle: '.sort-icon',
    animation: 150,
  }),
  customSortableId: '',
  forceRender: false,
  infiniteScrollImmediate: false,
  infiniteScrollDistance: 20,
  disabled: false,
  group: undefined,
  sort: true,
  allowCrossInstanceDrag: false,
})

const emits = defineEmits<{
  (event: 'update:modelValue', data: any): any
  (event: 'change', args: {
    action: 'sort' | 'remove' | 'add'
    value: any
    prevValue?: any
    originSortableId: string
    targetSortableId: string
    originData?: any
    targetData?: any
    originIndex?: number | string
    targetIndex?: number | string
  }): any
  (event: 'start', data: any): any
  (event: 'end', data: any): any
  (event: 'scroll', args: {
    scrollTop: number
  }): any
}>()
const id = `sort_${Math.random().toString(36).substr(2, 9)}`

const list = ref<any[]>([])
const renderFlag = ref(false)
const sortableId = computed(() => props.customSortableId || id)

onMounted(() => {
  initSortable()
})
onUnmounted(() => {
  destroySortable()
})

let _sortableInstance: any = null
let _removing = false
const initSortable = () => {
  if (props.disabled) return
  const sortableEl = document.querySelector(`#${sortableId.value}`)
  if (!sortableEl) return

  const sortableConfig: any = {
    group: props.group || (props.allowCrossInstanceDrag ? 'shared' : undefined),
    sort: props.sort,
    onStart: (event: any = {}) => {
      const { target, oldIndex } = event
      emits('start', event)
      if (target?.children?.[oldIndex]) {
        (target.children[oldIndex] as HTMLElement).style.background = props.dragBg
      }
    },
    onEnd: (event: any = {}) => {
      const { from = {}, to = {}, target, newIndex: targetIndex, oldIndex: originIndex } = event
      emits('end', event)
      if (target?.children?.[targetIndex]) {
        (target.children[targetIndex] as HTMLElement).style.background = 'transparent'
      }

      if (from === to && targetIndex !== originIndex) {
        if (_removing) return (_removing = false)
        const value = [...list.value]
        const prevValue = JSON.parse(JSON.stringify(value))
        const originData = value.splice(originIndex, 1)[0]
        const targetData = value[targetIndex]
        value.splice(targetIndex, 0, originData)
        list.value = value
        emits('update:modelValue', value)
        emits('change', {
          action: 'sort',
          prevValue,
          value,
          originSortableId: from.id,
          targetSortableId: to.id,
          originData,
          targetData,
          originIndex,
          targetIndex,
        })
      }
    },
    onAdd: (event: any = {}) => {
      const { from = {}, to = {}, target, newIndex: targetIndex, oldIndex: originIndex, item } = event
      if (target?.children?.[targetIndex]) {
        (target.children[targetIndex] as HTMLElement).style.background = 'transparent'
      }

      const value = [...list.value]
      const newItem = JSON.parse((item as HTMLElement).dataset.sortableData || '{}')
      value.splice(targetIndex, 0, newItem)
      list.value = value
      emits('update:modelValue', value)
      emits('change', {
        action: 'add',
        value,
        originSortableId: from.id,
        targetSortableId: to.id,
        originIndex,
        targetIndex,
        newItem,
      })
    },
    onRemove: (event: any = {}) => {
      const { from = {}, to = {}, target, newIndex: targetIndex, oldIndex: originIndex } = event
      if (target?.children?.[targetIndex]) {
        (target.children[targetIndex] as HTMLElement).style.background = 'transparent'
      }

      const value = [...list.value]
      const removedItem = value.splice(originIndex, 1)[0]
      list.value = value
      _removing = true
      emits('update:modelValue', value)
      emits('change', {
        action: 'remove',
        value,
        originSortableId: from.id,
        targetSortableId: to.id,
        originIndex,
        targetIndex,
        removedItem,
      })
    },
    ...props.props,
  }

  _sortableInstance = Sortable.create(sortableEl, sortableConfig)
}
const destroySortable = () => {
  if (_sortableInstance) {
    _sortableInstance.destroy()
    _sortableInstance = null
  }
}
let _scrollTop = 0
const handleScroll = () => {
  const sortableEl = document.querySelector(`#${sortableId.value}`)
  if (sortableEl) {
    _scrollTop = (sortableEl as HTMLElement).scrollTop || 0
  }
  emits('scroll', { scrollTop: _scrollTop })
}

const scrollToBottom = async () => {
  await nextTick()
  const sortableEl = document.querySelector(`#${sortableId.value}`)
  if (!sortableEl) return
  ;(sortableEl as HTMLElement).scrollTop = (sortableEl as HTMLElement).scrollHeight
}

const rerender = async () => {
  destroySortable()
  list.value = []
  renderFlag.value = true
  await nextTick()
  renderFlag.value = false
  await nextTick()
  list.value = [...props.modelValue]
  await nextTick()
  initSortable()
}
watch(
  () => props.modelValue,
  async () => {
    const { forceRender = false } = props
    if (forceRender) {
      await rerender()
    }
    list.value = [...props.modelValue]
    if (forceRender) {
      await nextTick()
      const sortableEl = document.querySelector(`#${sortableId.value}`)
      if (sortableEl) {
        (sortableEl as HTMLElement).scrollTop = _scrollTop
      }
    }
  },
  { immediate: true, deep: true }
)
watch(
  () => props.disabled,
  async () => {
    rerender()
  }
)

defineExpose({
  rerender,
  scrollToBottom,
})
</script>

<template>
  <div
    v-if="!renderFlag"
    :id="sortableId"
    v-infinite-scroll="handleScroll"
    :infinite-scroll-immediate="infiniteScrollImmediate"
    :infinite-scroll-distance="infiniteScrollDistance"
  >
    <slot name="header" />
    <template v-for="(item, index) in list" :key="(item && item[identity]) || index">
      <div :data-sortable-data="JSON.stringify(item)">
        <slot name="item" :item="item" :index="index" />
      </div>
    </template>
    <slot name="footer" />
  </div>
</template>

// web/packages/shared-components-react/src/Sortable/index.tsx
import React, {
  useEffect,
  useRef,
  useImperativeHandle,
  forwardRef,
  useCallback,
  useState,
} from "react";
import Sortable from "sortablejs";

export interface SortableChangeArgs {
  action: "sort" | "remove" | "add";
  value: any[];
  prevValue?: any[];
  originSortableId: string;
  targetSortableId: string;
  originData?: any;
  targetData?: any;
  originIndex?: number;
  targetIndex?: number;
  newItem?: any;
  removedItem?: any;
}

export interface SortableProps {
  /** 数据源 */
  value?: any[];
  /** 数据变化回调 */
  onChange?: (value: any[]) => void;
  /** 排序变化回调 */
  onSort?: (args: SortableChangeArgs) => void;
  /** 拖拽开始回调 */
  onDragStart?: (event: any) => void;
  /** 拖拽结束回调 */
  onDragEnd?: (event: any) => void;
  /** 唯一标识字段名，默认 'id' */
  identity?: string;
  /** 拖拽时的背景色 */
  dragBg?: string;
  /** 自定义 sortableId */
  customSortableId?: string;
  /** 是否禁用 */
  disabled?: boolean;
  /** sortablejs 配置 */
  sortableProps?: Sortable.Options;
  /** 渲染项 */
  renderItem: (item: any, index: number) => React.ReactNode;
  /** 渲染头部 */
  renderHeader?: () => React.ReactNode;
  /** 渲染底部 */
  renderFooter?: () => React.ReactNode;
  /** 容器样式 */
  style?: React.CSSProperties;
  /** 容器类名 */
  className?: string;
}

export interface SortableRef {
  rerender: () => void;
  scrollToBottom: () => void;
}

const generateId = () => `sort_${Math.random().toString(36).substr(2, 9)}`;

export const SortableComponent = forwardRef<SortableRef, SortableProps>(
  (
    {
      value = [],
      onChange,
      onSort,
      onDragStart,
      onDragEnd,
      identity = "id",
      dragBg = "#ECF5FF",
      customSortableId,
      disabled = false,
      sortableProps,
      renderItem,
      renderHeader,
      renderFooter,
      style,
      className,
    },
    ref
  ) => {
    const [sortableId] = useState(customSortableId || generateId);
    const containerRef = useRef<HTMLDivElement>(null);
    const sortableInstanceRef = useRef<Sortable | null>(null);
    const removingRef = useRef(false);
    const listRef = useRef<any[]>([]);

    // 同步 listRef
    useEffect(() => {
      listRef.current = [...value];
    }, [value]);

    const initSortable = useCallback(() => {
      if (disabled || !containerRef.current) return;

      // 销毁现有实例
      if (sortableInstanceRef.current) {
        sortableInstanceRef.current.destroy();
        sortableInstanceRef.current = null;
      }

      const config: Sortable.Options = {
        animation: 150,
        ...sortableProps,
        onStart: (event: Sortable.SortableEvent) => {
          onDragStart?.(event);
          const { target, oldIndex } = event;
          if (target?.children?.[oldIndex!]) {
            (target.children[oldIndex!] as HTMLElement).style.background = dragBg;
          }
        },
        onEnd: (event: Sortable.SortableEvent) => {
          const { from, to, target, newIndex, oldIndex } = event;
          onDragEnd?.(event);

          if (target?.children?.[newIndex!]) {
            (target.children[newIndex!] as HTMLElement).style.background = "transparent";
          }

          if (from === to && newIndex !== oldIndex) {
            if (removingRef.current) {
              removingRef.current = false;
              return;
            }

            const list = [...listRef.current];
            const prevValue = JSON.parse(JSON.stringify(list));
            const originData = list.splice(oldIndex!, 1)[0];
            const targetData = list[newIndex!];
            list.splice(newIndex!, 0, originData);

            listRef.current = list;
            onChange?.(list);
            onSort?.({
              action: "sort",
              prevValue,
              value: list,
              originSortableId: from.id,
              targetSortableId: to.id,
              originData,
              targetData,
              originIndex: oldIndex,
              targetIndex: newIndex,
            });
          }
        },
        onAdd: (event: Sortable.SortableEvent) => {
          const { from, to, target, newIndex, oldIndex, item } = event;

          if (target?.children?.[newIndex!]) {
            (target.children[newIndex!] as HTMLElement).style.background = "transparent";
          }

          const list = [...listRef.current];
          const newItem = JSON.parse((item as HTMLElement).dataset.sortableData || "{}");
          list.splice(newIndex!, 0, newItem);

          listRef.current = list;
          onChange?.(list);
          onSort?.({
            action: "add",
            value: list,
            originSortableId: from.id,
            targetSortableId: to.id,
            originIndex: oldIndex,
            targetIndex: newIndex,
            newItem,
          });
        },
        onRemove: (event: Sortable.SortableEvent) => {
          const { from, to, target, newIndex, oldIndex } = event;

          if (target?.children?.[newIndex!]) {
            (target.children[newIndex!] as HTMLElement).style.background = "transparent";
          }

          const list = [...listRef.current];
          const removedItem = list.splice(oldIndex!, 1)[0];

          listRef.current = list;
          removingRef.current = true;
          onChange?.(list);
          onSort?.({
            action: "remove",
            value: list,
            originSortableId: from.id,
            targetSortableId: to.id,
            originIndex: oldIndex,
            targetIndex: newIndex,
            removedItem,
          });
        },
      };

      sortableInstanceRef.current = Sortable.create(containerRef.current, config);
    }, [disabled, dragBg, onChange, onDragEnd, onDragStart, onSort, sortableProps]);

    const destroySortable = useCallback(() => {
      if (sortableInstanceRef.current) {
        sortableInstanceRef.current.destroy();
        sortableInstanceRef.current = null;
      }
    }, []);

    useEffect(() => {
      initSortable();
      return destroySortable;
    }, [initSortable, destroySortable]);

    // disabled 变化时重新初始化
    useEffect(() => {
      destroySortable();
      initSortable();
    }, [disabled, destroySortable, initSortable]);

    const scrollToBottom = useCallback(() => {
      if (containerRef.current) {
        containerRef.current.scrollTop = containerRef.current.scrollHeight;
      }
    }, []);

    const rerender = useCallback(() => {
      destroySortable();
      initSortable();
    }, [destroySortable, initSortable]);

    useImperativeHandle(ref, () => ({
      rerender,
      scrollToBottom,
    }));

    return (
      <div
        ref={containerRef}
        id={sortableId}
        style={style}
        className={className}
      >
        {renderHeader?.()}
        {value.map((item, index) => (
          <div
            key={(item && item[identity]) || index}
            data-sortable-data={JSON.stringify(item)}
          >
            {renderItem(item, index)}
          </div>
        ))}
        {renderFooter?.()}
      </div>
    );
  }
);

SortableComponent.displayName = "Sortable";

export default SortableComponent;
